### ISSUE TITLE
Waiting for phone to connect galaxy s3

### ISSUE THREAD

**Issue by unixndata** [kosborn/p2p-adb#6] opened 2012-10-06 03:46 UTC
Hey mate,

Installed it as your post etc and i load it up and it keeps saying waiting to connect...

I have tried IOS devices and android but i always get waiting for phone to connect, is there an issue with the s3's ?

Cheers

**Comment by kosborn** [comment] 2012-10-06 05:22
I need a little more info. What device is it loaded on? Are all prerequisites met (root, busybody, running it as root, have a USB OTG cable, etc).  Is the device you're connected have adb enabled? p2p-adb doesn't do anything against iOS devices.

**Comment by unixndata** [comment] 2012-10-06 05:32
Phones running root, busybox, 4.0.4 android has su priv's, the device's I tried where factory android devices. I tried to get the gallery of the other phone has per your hak5 video to no avail either, is there a trick to it ? mtp is enabled on my s3 and i connect to the ios and it just charges it etc. also have USB OTG cable.

Cheers

**Comment by unixndata** [comment] 2012-10-06 05:44
Here is a link to my screen

http://s16.postimage.org/yl8ncngj9/Screenshot_2012_10_06_15_40_50.png

**Comment by darKpoiSon** [comment] 2012-10-06 09:02
had this problem aswell.. I don't know if its on every phone, but on the Galaxy S3 adb is always running. The problem is, it's not running as root, but it has to.
So either stop and start the adb server manually using:
<code>adb kill-server
su
adb start-server
</code>
or write in in the functions.sh script.

kosborn:
I would change the script to automatically stop and start the adb server. It doesn't take that long, but you're sure it's running as root

**Comment by Hackrylix** [comment] 2012-10-06 12:06
Same issue if not running as root. Fixed by killing and relaunching with su (or sudo) !
Maybe just should be added in the script start.
I'm working on a platform switch (launched on a phone/a computer) : 
- Busybox ON/OFF
- adb path + su (or sudo)
- Little gui on computers ?

Will it be useful ?

Cheers

**Comment by unixndata** [comment] 2012-10-06 12:14
yeah it would. Will try this out as soon as i can.

Cheers

**Comment by kosborn** [comment] 2012-10-06 18:02
ADB server running without root privs appears to be a common issue. I'll address it with adb kill-server and su -c 'adb start-server'. That should be sufficient to solve most problems.

**Comment by kosborn** [comment] 2012-10-08 19:44
@Hackrylix About a switch for desktop, what's the point exactly? The code should run fine on just about any vanilla linux install with adb. Busybox can be disabled manually in run.sh. Also, I will not officially support any GUI for any machine (android, linux, os x, windows), so I can maintain compatibility, and size, of the project. It already bums me out that I've had to include binaries in the project, but it's a necessary evil).

You can fork/create a new project that contains the GUI, and I encourage it. I'm even working on making it easier to dynamically generate a list of modules and going to build a wrapper specifically for a GUI (I actually would really like an Android GUI utilizing this soon to be pushed method.)

**Closed as completed** 2012-10-08 21:09 UTC
Labels: bug
